#Setting datatype for the value
x = int(20)
print(x,type(x))

print("string datatype: ",type("apple"))
print("int datatype: ",type(5))
print("float datatype: ",type(5.0))
print("list datatype: ",type(["apple","orange"]))
print("tuple datatype: ",type(("apple","orange")))
print("range datatype: ",type(range(2)))
print("dict datatype: ",type({"IndiaState1":"Goa","IndiaState2":"Haryana"}))
print("frozen datatype: ",type(frozenset({"apple", "banana", "cherry"})))
print("bool datatype: ",type(bool(5>2)))
print("bytes datatype: ",type(b'hello'))
print("bytearray datatype: ",type(bytearray(5)))