apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-dep
  labels:
    name: worker-dep
    app: demovoting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-app-pod
      app: demovoting-app
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: demovoting-app
    spec:
      containers:
        - name: worker-app
          image: dockersamples/examplevotingapp_worker